import React from "react";
import Head from "next/head";

import "@/styles/globals.css";
import styles from "@/styles/pages/App.module.scss";
import "react-awesome-slider/dist/styles.css";

import type { AppProps } from 'next/app'

export function reportWebVitals(metric) {
  console.log(metric)
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Elastic Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <Component {...pageProps} />
      </div>


    </div>
  );
}

export default MyApp;
